{
 "title": "Resolver Events",
 "description": "Events occurring in the Battletech Damage Resolver",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Game Events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(eventtime,$__interval),\n  count(actiondata) AS \"Player Logins\"\nFROM resolverloggame\nWHERE\n  $__timeFilter(eventtime) AND\n  actiontype = '0'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(eventtime,$__interval),\n  count(actiondata) AS \"Turns Played\"\nFROM resolverloggame\nWHERE\n  $__timeFilter(eventtime) AND\n  actiontype = '2'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(eventtime,$__interval),\n  count(DISTINCT gameid) AS \"Active Games\"\nFROM resolverloggame\nWHERE\n  $__timeFilter(eventtime)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Player Events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(eventtime,$__interval),\n  sum(actiondata) AS \"Player Logins\"\nFROM resolverlogplayer\nWHERE\n  $__timeFilter(eventtime) AND\n  actiontype = '0'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(eventtime,$__interval),\n  count(DISTINCT playerId) AS \"Active Users\"\nFROM resolverlogplayer\nWHERE\n  $__timeFilter(eventtime)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Unit Events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(eventtime,$__interval),\n  count(actiondata) AS \"Unit Updates\"\nFROM resolverlogunit\nWHERE\n  $__timeFilter(eventtime) AND\n  actiontype = '1'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(eventtime,$__interval),\n  count(actiondata) AS \"Fire Events\"\nFROM resolverlogunit\nWHERE\n  $__timeFilter(eventtime) AND\n  actiontype = 0\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(eventtime,$__interval),\n  count(DISTINCT unitid) AS \"Active Units\"\nFROM resolverlogunit\nWHERE\n  $__timeFilter(eventtime)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  }
 ]
}